export const __mockReviews = [
  {
    firstName: 'John',
    lastName: 'Doe',
    file: 'review1.pdf',
    date: '2024-01-15',
    content: 'Great product, highly recommend!',
    rate: 5,
  },
  {
    firstName: 'Jane',
    lastName: 'Smith',
    file: 'review2.pdf',
    date: '2024-02-10',
    content: 'The product was good, but the delivery was delayed.',
    rate: 4,
  },
  {
    firstName: 'Alice',
    lastName: 'Johnson',
    file: 'review3.pdf',
    date: '2024-03-05',
    content: 'Average quality, not as expected.',
    rate: 3,
  },
  {
    firstName: 'Bob',
    lastName: 'Williams',
    file: 'review4.pdf',
    date: '2024-04-20',
    content: 'Poor quality, would not buy again.',
    rate: 2,
  },
  {
    firstName: 'Carol',
    lastName: 'Brown',
    file: 'review5.pdf',
    date: '2024-05-18',
    content: 'Terrible experience, the product was damaged.',
    rate: 1,
  },
];
